apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: petclinic
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: saniatk1985/docker-project:latest
        
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASS
          - name: DB_PORT
            value: "3306"
          - name: DB_HOST
            value: db-service
        ports:
        - containerPort: 8080
          hostPort: 8080

