
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mariadb
  type:  ClusterIP
  ports:
  - port:  3306
    targetPort:  3306
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:5
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_ROOT_PASsWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_NAME
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASS
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-persistent-volume-claim    