---
- hosts: db 
  name: Install MySQL database
  become: yes
  gather_facts: yes

    
  tasks:
      - name: Install DataBase
        yum: pkg=mysql-server state=present update_cache=yes
            
      - name: Install OS packages
        yum: name={{item}} state=present
        with_items:
        - mysql-devel
        - gcc
        - python-devel
        - MySQL-python

      - name: Install MySQL-Python  module
        pip: name=MySQL-python

        #check if mysql service is started
      - name: Start the MySQL service
        service: 
            name: mysqld
            state: started
            enabled: true

      - name: Removes all anonymous user accounts
        mysql_user:
            name: ''
            host_all: yes
            state: absent

      - name: Removes test database
        mysql_db:
            name: test
            state: absent

      - name: Create new database
        mysql_db:
            name: "{{ db_name }}" #'{{ lookup("env", "DB_NAME") }}'
            state: present
      

      - name: Create new database user
        mysql_user:
            name: "{{ db_user }}" #'{{ lookup("env", "DB_USER") }}'
            password: "{{ db_pass }}" #'{{ lookup("env", "DB_PASS") }}'
            priv: '{{ db_name }}.*:ALL,GRANT' # need to check this
            host: '10.0.0.%'
            state: present
      - name: test
        debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

      - name: Check that user can connect to database
        mysql_db:
            login_user: "{{ db_user }}" #'{{ lookup("env", "DB_USER") }}'
            login_password: "{{ db_pass }}" #'{{ lookup("env", "DB_PASS") }}'
            login_host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
            login_port: "{{ db_port }}" #'{ lookup("env", "DB_PORT") }}'
            name: "{{ db_name }}"
            state: present

